repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-case-conflict
    -   id: check-byte-order-marker
    -   id: check-added-large-files
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: mixed-line-ending
        args: [ --fix, lf ]
-   repo: https://github.com/AleksaC/hadolint-py
    rev: v2.12.0
    hooks:
    -   id: hadolint
        args: [--ignore, DL3008, --ignore, DL4006]
-   repo: local
    hooks:
    -   id: forbid-tabs
        name: forbid tabs
        language: pygrep
        entry: '\t'
        types: [text]
